import { NextRequest, NextResponse } from "next/server";
import Replicate from "replicate";
import { getGeminiClient } from "@/lib/gemini";

export const maxDuration = 120;

type Provider = "replicate" | "google";

interface ThumbnailRequest {
  prompt: string;
  negativePrompt?: string;
  provider: Provider;
  aspectRatio: string;
  referenceImages?: { data: string; mimeType: string }[];
  apiKey: string;
  resolution?: string;
  outputFormat?: string;
  model?: string;
}

async function generateWithReplicate(body: ThumbnailRequest) {
  const replicate = new Replicate({ auth: body.apiKey });

  const input: Record<string, unknown> = {
    prompt: body.prompt,
    aspect_ratio: body.aspectRatio || "16:9",
    output_format: body.outputFormat || "png",
  };

  if (body.negativePrompt) {
    input.negative_prompt = body.negativePrompt;
  }

  if (body.resolution) {
    input.resolution = body.resolution;
  }

  if (body.referenceImages && body.referenceImages.length > 0) {
    input.image_input = body.referenceImages.map(
      (img) => `data:${img.mimeType};base64,${img.data}`
    );
  }

  console.log(
    `[thumbnail] Replicate — prompt: "${body.prompt.slice(0, 80)}...", ratio: ${body.aspectRatio}, refs: ${body.referenceImages?.length ?? 0}`
  );

  const output = await replicate.run("google/nano-banana-pro", { input });

  const fileOutput = output as { url(): string } | string;
  let imageUrl: string;

  if (typeof fileOutput === "string") {
    imageUrl = fileOutput;
  } else if (typeof fileOutput === "object" && fileOutput !== null && "url" in fileOutput) {
    imageUrl = (fileOutput as { url(): string }).url();
  } else if (Array.isArray(output) && output.length > 0) {
    const first = output[0];
    imageUrl =
      typeof first === "string"
        ? first
        : typeof first?.url === "function"
          ? first.url()
          : String(first);
  } else {
    throw new Error("Unexpected Replicate output format");
  }

  return NextResponse.json({ imageUrl, provider: "replicate" });
}

async function generateWithGoogle(body: ThumbnailRequest) {
  const genAI = getGeminiClient(body.apiKey);
  const selectedModel = body.model || "gemini-2.5-flash-image";
  const imageAspectRatio = body.aspectRatio || "16:9";

  const parts: { text?: string; inlineData?: { mimeType: string; data: string } }[] =
    [];

  const negativeClause = body.negativePrompt
    ? `\n\nIMPORTANT — Do NOT include any of the following: ${body.negativePrompt}`
    : "";

  if (body.referenceImages && body.referenceImages.length > 0) {
    for (const ref of body.referenceImages) {
      parts.push({
        inlineData: {
          mimeType: ref.mimeType || "image/png",
          data: ref.data,
        },
      });
    }
    parts.push({
      text: `[REFERENCE IMAGES ABOVE]: Use these as style and composition guidance. Generate a SINGLE image that fills the ENTIRE canvas edge-to-edge. NO borders, NO panels, NO frames.\n\n${body.prompt}${negativeClause}`,
    });
  } else {
    parts.push({
      text: `Generate a SINGLE image that fills the ENTIRE canvas edge-to-edge. NO borders, NO panels, NO frames.\n\n${body.prompt}${negativeClause}`,
    });
  }

  console.log(
    `[thumbnail] Google — model: ${selectedModel}, prompt: "${body.prompt.slice(0, 80)}...", ratio: ${imageAspectRatio}, refs: ${body.referenceImages?.length ?? 0}`
  );

  const response = await genAI.models.generateContent({
    model: selectedModel,
    contents: [{ role: "user", parts }],
    config: {
      responseModalities: ["image", "text"],
      imageConfig: { aspectRatio: imageAspectRatio },
    },
  });

  let imageBase64: string | null = null;
  let mimeType: string | null = null;

  if (response.candidates?.[0]?.content?.parts) {
    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData?.data) {
        imageBase64 = part.inlineData.data;
        mimeType = part.inlineData.mimeType || "image/png";
        break;
      }
    }
  }

  if (!imageBase64) {
    const text = response.text || "";
    throw new Error(
      text.includes("SAFETY") || text.includes("blocked")
        ? "Image was blocked by safety filters. Try rephrasing the prompt."
        : "No image generated by the model. Try a different prompt or model."
    );
  }

  return NextResponse.json({ imageBase64, mimeType, provider: "google" });
}

export async function POST(req: NextRequest) {
  try {
    const body: ThumbnailRequest = await req.json();

    if (!body.prompt?.trim()) {
      return NextResponse.json(
        { error: "Prompt is required" },
        { status: 400 }
      );
    }

    if (!body.apiKey?.trim()) {
      return NextResponse.json(
        { error: "API key is required. Add it in the API Keys page." },
        { status: 401 }
      );
    }

    if (body.provider === "replicate") {
      return await generateWithReplicate(body);
    }

    return await generateWithGoogle(body);
  } catch (err: unknown) {
    const message =
      err instanceof Error ? err.message : "Thumbnail generation failed";
    console.error("[thumbnail] Error:", message);
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
