import { NextRequest, NextResponse } from "next/server";
import { getGeminiClient } from "@/lib/gemini";

async function sleep(ms: number) {
  return new Promise((r) => setTimeout(r, ms));
}

const FALLBACK_MODELS = [
  "gemini-2.5-flash-image",
  "gemini-3.1-flash-image-preview",
];

export async function POST(request: NextRequest) {
  try {
    const { prompt, apiKey, model, referenceImage } = await request.json();

    if (!prompt || typeof prompt !== "string") {
      return NextResponse.json(
        { error: "invalid_input", message: "Prompt is required", retryable: false },
        { status: 400 }
      );
    }

    if (!apiKey || typeof apiKey !== "string") {
      return NextResponse.json(
        { error: "missing_api_key", message: "Gemini API key is required", retryable: false },
        { status: 400 }
      );
    }

    const genAI = getGeminiClient(apiKey);
    let imageBase64: string | null = null;
    let mimeType: string | null = null;
    let lastError: string = "";

    const modelsToTry = model && typeof model === "string"
      ? [model, ...FALLBACK_MODELS.filter((m) => m !== model)]
      : FALLBACK_MODELS;

    // Build parts array — text + optional reference image
    const parts: { text?: string; inlineData?: { mimeType: string; data: string } }[] = [];

    if (referenceImage && typeof referenceImage === "object" && referenceImage.data) {
      parts.push({
        inlineData: {
          mimeType: referenceImage.mimeType || "image/png",
          data: referenceImage.data,
        },
      });
      parts.push({
        text: `[REFERENCE SCREENSHOT ABOVE]: This is Scene 1 from the animated video. Your generated image MUST match this reference exactly — same characters, same art style, same colors, same line weight. Generate a SINGLE fullscreen scene that fills the ENTIRE canvas edge-to-edge. NO borders, NO panels, NO frames, NO margins, NO white space. One continuous scene like a movie screenshot.\n\n${prompt}`,
      });
      console.log(`[generate-scene] Using reference image anchoring (${Math.round(referenceImage.data.length / 1024)}KB)`);
    } else {
      parts.push({ text: prompt });
    }

    for (const modelId of modelsToTry) {
      if (imageBase64) break;

      for (let attempt = 0; attempt < 2; attempt++) {
        try {
          console.log(`[generate-scene] Trying ${modelId} (attempt ${attempt + 1})`);

          const response = await genAI.models.generateContent({
            model: modelId,
            contents: [{ role: "user", parts }],
            config: {
              responseModalities: ["image", "text"],
            },
          });

          if (response.candidates && response.candidates[0]?.content?.parts) {
            for (const part of response.candidates[0].content.parts) {
              if (part.inlineData) {
                imageBase64 = part.inlineData.data || null;
                mimeType = part.inlineData.mimeType || "image/png";
                break;
              }
            }
          }

          if (imageBase64) {
            console.log(`[generate-scene] Success with ${modelId}`);
            break;
          }
        } catch (err: unknown) {
          lastError = err instanceof Error ? err.message : String(err);
          console.log(`[generate-scene] ${modelId} attempt ${attempt + 1} failed:`, lastError);

          const isRateLimit =
            lastError.includes("429") ||
            lastError.includes("RESOURCE_EXHAUSTED");

          const isNotFound = lastError.includes("404") || lastError.includes("NOT_FOUND");

          if (isNotFound) {
            console.log(`[generate-scene] Model ${modelId} not available, skipping`);
            break;
          }

          if (isRateLimit && attempt === 0) {
            console.log(`[generate-scene] Rate limited on ${modelId}, waiting 20s...`);
            await sleep(20000);
            continue;
          }

          break;
        }
      }
    }

    if (!imageBase64) {
      if (lastError.includes("SAFETY") || lastError.includes("blocked")) {
        return NextResponse.json(
          {
            error: "content_blocked",
            message: "Scene was flagged by safety filters. Edit the description and retry.",
            retryable: false,
          },
          { status: 422 }
        );
      }

      if (lastError.includes("429") || lastError.includes("RESOURCE_EXHAUSTED")) {
        return NextResponse.json(
          {
            error: "rate_limited",
            message: "API rate limit hit. The app will auto-retry with backoff.",
            retryable: true,
          },
          { status: 429 }
        );
      }

      return NextResponse.json(
        {
          error: "generation_failed",
          message: lastError || "No image generated by the model.",
          retryable: true,
        },
        { status: 500 }
      );
    }

    return NextResponse.json({ image_base64: imageBase64, mime_type: mimeType });
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : "Image generation failed";
    return NextResponse.json(
      { error: "generation_failed", message, retryable: true },
      { status: 500 }
    );
  }
}
